apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spotify-party-api
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        deployVersion: "1.1.0-8"
        prometheus.io/scrape: 'false'
      labels:
        app: spotify-party-api
    spec:
      containers:
        - image: gcr.io/airglide-166614/spotify-party-api:1.0-SNAPSHOT
          name: spotify-party-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 220M
            limits:
              cpu: 1000m
              memory: 960M
          env:
            - name: API_HOST
              value: http://partify.quirlion.com
            - name: SPOTIFY_CLIENT_ID
              value: 10a4963dcc5c472b8d5c52004d08cb43
            - name: SPOTIFY_CLIENT_SECRET
              value: cbabbc30e3aa46939524689d9421a808
            - name: NODE_HOSTNAME
              valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
            - name: GCP_PROJECT
              value: airglide-166614
          ports:
            - containerPort: 8080
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
            
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-party-api
  labels:
    app: spotify-party-api
spec:
  selector:
    app: spotify-party-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer